services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Back.Dockerfile
    container_name: hotel-backend
    ports:
      - "3000:3000"
    env_file:
      - apps/backend/.env
    volumes:
      - backend_db_data:/app/prisma/dev.db
    networks:
      - hotel-net

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Front.Dockerfile
    container_name: hotel-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - hotel-net

networks:
  hotel-net:
    driver: bridge

volumes:
  backend_db_data:
